version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: prompttrim
      POSTGRES_USER: prompttrim_user
      POSTGRES_PASSWORD: prompttrim_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prompttrim_user -d prompttrim"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PromptTrim API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://prompttrim_user:prompttrim_password@postgres:5432/prompttrim
      - REDIS_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=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
      - FROM_EMAIL=noreply@prompttrim.com
      - SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./models_cache:/app/models_cache
    restart: unless-stopped

volumes:
  postgres_data:
